---
- name: Check if polybar was installed via source
  ansible.builtin.stat:
    path: /usr/local/bin/polybar
  register: polybar_executable

- name: Print polybar executable details
  ansible.builtin.debug:
    msg: "{{ polybar_executable }}"

- name: Install polybar
  block:
    - name: Install polybar via package manager
      ansible.builtin.package:
        name: polybar
        state: present
      ignore_errors: yes
      become: yes
      register: installed

    - name: Log failure to install polybar via package manager
      ansible.builtin.debug:
        msg: Unable to install polybar via the package manager. Will try building from source.
      when: installed.failed

    - name: Build polybar from source
      ansible.builtin.include_tasks: build.yml
      when:
        - installed.failed
  when: not polybar_executable.stat.exists

- name: Install net-tools for IP info in bottom polybar
  ansible.builtin.package:
    name: net-tools
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Create Polybar config directory
  ansible.builtin.file:
    path: "{{ polybar_config_dir }}"
    state: directory
    mode: "0755"

- name: Copy Polybar config
  ansible.builtin.template:
    src: templates/config
    dest: "{{ polybar_config_dir }}"
    mode: "0644"

- name: Copy launchpolybar script
  ansible.builtin.template:
    src: templates/launchpolybar.sh
    dest: "{{ polybar_config_dir }}/launchpolybar.sh"
    mode: "0744"

- name: Copy localip script for Polybar
  ansible.builtin.template:
    src: templates/localip.sh
    dest: "{{ polybar_config_dir }}/localip.sh"
    mode: "0744"