---
- name: Install misc packages
  ansible.builtin.package:
    name:
      - pavucontrol
      - gnome-calendar
      - git
      - curl
      - tree
      - feh
    state: present
  become: yes

- name: Create wallpaper dir
  ansible.builtin.file:
    path: "{{ wallpapers_dir }}"
    state: directory
    mode: "0755"

- name: Copy wallpaper
  ansible.builtin.copy:
    src: files/mountains.png
    dest: "{{ wallpapers_dir }}"