---
- name: Install misc packages
  ansible.builtin.package:
    name:
      - pavucontrol
      - gnome-calendar
      - git
      - curl
      - tree
      - feh
      - autorandr
      - flameshot
    state: present
  become: yes

- name: Create wallpaper dir
  ansible.builtin.file:
    path: "{{ wallpapers_dir }}"
    state: directory
    mode: "0755"

- name: Copy wallpaper
  ansible.builtin.copy:
    src: files/mountains.png
    dest: "{{ wallpapers_dir }}"

- name: Create autorandr config dir 
  ansible.builtin.file:
    path: "{{ autorandr_config_dir }}"
    state: directory
    mode: "0755"

- name: Copy autorandr postswitch script
  ansible.builtin.template:
    src: templates/postswitch
    dest: "{{ autorandr_config_dir }}"
    mode: "0744"

- name: Create flameshot config dir 
  ansible.builtin.file:
    path: "{{ flameshot_config_dir }}"
    state: directory
    mode: "0755"

- name: Copy flameshot config
  ansible.builtin.template:
    src: templates/flameshot.ini
    dest: "{{ flameshot_config_dir }}"
    mode: "0644"