---
- name: Install pavucontrol
  ansible.builtin.package:
    name: pavucontrol
    state: present
  become: yes

- name: Install gnome-calendar
  ansible.builtin.package:
    name: gnome-calendar
    state: present
  become: yes